Secrets
awsjavakit/aws-java-kit pull request #32
Opened 2023-09-13 13:46 UTC by axthosarouris

2023-09-14 13:40 UTC, axthosarouris commented on secrets/src/test/java/com/githhub/awsjavakit/secrets/SecretsReaderTest.java
> +  @Test
Here we have a major change in functionality. In NVA we were hiding which secret we were trying to read. Here, however the exception reveals the sercret name (but not the value). The secret name exists as a parameter (not a secret parameter) so in a way the secret name is not a secret in itself. If however the client needs to hide the secret name, they can do so by catching the exception.

2023-09-14 15:04 UTC, brinxmat requested changes

2023-09-14 15:04 UTC, brinxmat commented on secrets/src/main/java/com/githhub/awsjavakit/secrets/SecretsReader.java
> +    var secretDetailsString = String.join(":", secretDetails);
Probably constant for the. ":"

2023-09-15 06:53 UTC, brinxmat approved these changes

2023-09-15 07:20 UTC, merged